# Generated by Django 6.0.2 on 2026-03-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_job_is_active_job_end_date_job_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-resume_score']},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='hr_notes',
            new_name='hr_decision_notes',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='interview_score',
            new_name='hr_score',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='similarity_score',
            new_name='resume_score',
        ),
        migrations.RemoveField(
            model_name='application',
            name='interview_date',
        ),
        migrations.AddField(
            model_name='application',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('selected', 'Selected'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hr_attended',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hr_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='system_recommendation',
            field=models.CharField(blank=True, choices=[('selected', 'Selected'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='technical_attended',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='technical_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='technical_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='technical_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('not_shortlisted', 'Not Shortlisted'), ('shortlisted', 'Shortlisted'), ('technical_scheduled', 'Technical Interview Scheduled'), ('technical_completed', 'Technical Interview Completed'), ('hr_scheduled', 'HR Interview Scheduled'), ('hr_completed', 'HR Interview Completed'), ('system_recommended', 'System Recommended'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=30),
        ),
    ]
