# Generated by Django 6.0.2 on 2026-03-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hr_interviewer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='hr_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='technical_interviewer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='technical_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
