# Generated by Django 6.0.2 on 2026-05-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_profile_image_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='missing_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
